[build]
  functions = "netlify/functions"

[build.environment]
  NETLIFY_ENABLE_DRAWER = "false"

[context.production.environment]
  NETLIFY_ENABLE_DRAWER = "false"

[context.deploy-preview.environment]
  NETLIFY_ENABLE_DRAWER = "false"

[context.branch-deploy.environment]
  NETLIFY_ENABLE_DRAWER = "false"

[[redirects]]
  from = "/api/mcx-rates"
  to = "/.netlify/functions/mcx-rates"
  status = 200
