[build.environment]
  NETLIFY_ENABLE_DRAWER = "false"

[context.production.environment]
  NETLIFY_ENABLE_DRAWER = "false"

[context.deploy-preview.environment]
  NETLIFY_ENABLE_DRAWER = "false"

[context.branch-deploy.environment]
  NETLIFY_ENABLE_DRAWER = "false"
